# Test: Required Labels Policy Violation
# Policy: required-labels / require-standard-labels (Gatekeeper & Kyverno)
#
# This test resource violates the policy by not having required labels.
# Expected behavior:
#   - Gatekeeper: Should create violation (if enforcementAction: deny, will block)
#   - Kyverno: Should create violation (if validationFailureAction: Enforce, will block)
#
# To verify violations:
#   Gatekeeper: kubectl get k8srequiredlabels.constraints.gatekeeper.sh required-labels -o yaml
#   Kyverno: kubectl get clusterpolicy require-standard-labels -o yaml
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-no-labels
  namespace: policy-tests-violations
  # VIOLATION: Missing required labels (e.g., app.kubernetes.io/name, app.kubernetes.io/version)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-container
        image: busybox:1.36
        command: ['sh', '-c', 'sleep 3600']
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000

