# SealedSecret for NAI image registry credentials
# This sealed secret uses cluster-wide scope so it can be used from any namespace
# NOTE: This requires all target clusters to have the same sealed-secrets controller private key.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: nai-image-pull-secret
  namespace: nai-system
spec:
  encryptedData:
    .dockerconfigjson: AgBm+OG5/hKzF/1DI0qMFtH9lyF2kFO9WHD0jJ8V+r4+iF1P6MkcsC8hAOzLh31eGEXaHL4tMq99rDP+aay0iM7cXqCjODJOipAN8J21HCBbK99YMJnFkmZkaDI6zzJImT15/Y5VOpGrKEm7ogpdwOOLdDn4qRqTdyQa5jVhgJn6Zzw9eLhBC+WwCBw1XRMavUiiIf4ttizBf/6dyqwXmmkhDRZBCHZp1/FzCPVdHOYbCu5spI4Dxs2suJCi/4e+slzgGX+0NDJYI+81TJqIzMmbjhkRBNE/Fm85RpYXF7jcj39QuK1V5s/cNVNdPRVuNN9QkHRobfTHvnw4aQATelhB/GpICK/mobjfz7hJdI2ptpF3lfJdO9LAYDyyO5Bo2dqTjD7Q2wgN4mm1bIGilH/Q2e1QxDln+zj0QdBtWp9i+hcs4Wq00cx5XfQyCfTZfjDulZPM3qnskHG/F1H5A0pIgtW3O4FIcZU1E7rT7P/xq5n63ihbspphknIMCBYOJcIRRBBmx4Jyu9Y3MGWsY4wruGmPiZB7xrnaa0GPlAHb6ah1kLtxpbktDZ0MX9HRqzvrUU7h/vAypfLB1KmQ/kGtAIQCrP//XCk9JWVkUT+f7esayL+wo4qSHrkKcg8nZBJ7acvnd+uvgPEQ7CwwTuraUQDfM1q8ImTE+kBkRzZcCeYf4CFPF+Svdq8Er+3WGq1xJGHpn2RYmnh/fMXGJePjuVPnGiDv6trUZyxgkvaXvLn5Gp+YuXKbVdIITgKxA3s/vDc5EbiLBRqyZHQbgdkMj/AMQUQwi49hsKDdjegv1UjKSRKExluLnhlo9XbHkZJojopIhO5VC1CWUNckU+ZTnJmAbYiU5rsoa3Nm6X1+0e/QfAFM9/c5kjbU3KJUgBqqcsvo+n/+xlUP7/YHyQBMWhboUnzYiAHvYug27g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: nai-image-pull-secret
      namespace: nai-system
    type: kubernetes.io/dockerconfigjson
