# SealedSecret for NAI image registry credentials
# This sealed secret uses cluster-wide scope so it can be used from any namespace
# NOTE: This requires all target clusters to have the same sealed-secrets controller private key.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: nai-image-pull-secret
  namespace: nai-system
spec:
  encryptedData:
    .dockerconfigjson: AgBk63sI4CKCm84bK0AISX+/WhWYhJ2EUy6ZvYYDXytSNKMUVzCy8GSOiP7tF5GvwVOwLgCrxswLWRMcN5JX2JMScVUcO1GNyz1XCJCp9wmJBIrzWK0QBvME2sUz1LhHTIdl3Z2X2nGSdsvfXBy2SK2YLADHRWLsxEOYlzv+fGngTHKTxpzqgiaEwQsmteYwmNGjuCXdgiVvG8MFCG8yIGntQLqkkF6IFMR7KM/gJRV2lHlCuRqNUiGb/H9Wq3Bm7YswwC4jyx4gFeyDb8JRFfc0tLoAOGAjqArGtI00YVHC2QzGfSlpoL0uAFTFnRMsioOPCdgcF9qDw0bNPBTzvhkq22oV/n7QDn3clZoz8JzLFsfkPJnfn0ej0rgPAmOzuXPKGQSlt0xXIw7vZ62hu8gfbQQc8oKFT8fBnYRAczFkUHxy0LOS/u13U13AZohxhPDTQRHKFRj+nocwG7+fJ9Y/8gaBeRMasffWjS129n21TwD1nrH6JqvTt5DC7PledTqQntxs9GGzjpX5bKN7E5Sn15BUhhdeV6Z9XjelPdE0yPSc54IM6w/a2xr18HEq15pUmTlIxz7lqxjdXH7YuFRld92qQytGvt0Jme65hI5P88qBrhqRg95BrevxXSrWnU/zpouDLjMt0Z3wFLnQgtYBlyciwt/PD8HrsEGEx+VFqiEv/ANaML6XJt30zojcLtwYiog3/H0bZ2i8y28cRCM/bpT/FzgywAPkImD7dJjoF2qMRgc0V4KjsdiDDHZcE+GqkUW0UqNPgLDcnIjpQJBLceyePZzmMcpTfo1LD6gP49Yh5NnUgke3Ox5R0SHW5mvs9iUMMbONm4prAA0cPeCf6fkqDcBBogEE65srIk13x4lFQ3DKPtX+d6j7DSqjd/sKjdyg9HVoY47NtrNji0+7yqlCsILsiQekuEOT4F6qkW7nxlvN0wPt
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: nai-image-pull-secret
      namespace: nai-system
    type: kubernetes.io/dockerconfigjson
