# SealedSecret for NAI image registry credentials
# This sealed secret uses cluster-wide scope so it can be used from any namespace
# NOTE: This requires all target clusters to have the same sealed-secrets controller private key.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: nai-image-pull-secret
  namespace: nai-system
spec:
  encryptedData:
    .dockerconfigjson: AgCX7i0/eEwoROJMqbgQ/HmQHxU1SZ755sdFf97WSztkOpw/CwvMfTXM3tEL87xDxhBsZsc1bBCa+zBc9qmmI/gQH+PbR3sU9pNh74YqqN0w5szxrwS42Ozg0aoRfqptUPq1VSTFIVo/NfhVGPC8Vd8APCjecx9ShOvNJJHkad5xYA2i2pHSsrg2PNdKaa7tUxCoy3n08uMPNTl3+i1tahEP/BAH68rDITcKZd4m2v4n2hVpCk0sx6gCo+tMwtwRu2rzVBaU187/NXLW/W3aWrxLS+5C+wEZRuGGF/jXVqF9zV3U1v28/JCsphS7lL/JahO4ruTegO/qsR2vpcPYXpQOf0FzCLK8+y+zRPMSEpYx26pbV1nRaOlrXayNsPAdb+ZMFWAf7UJ4NRtolGY7N44v0rEyiTxg4YZb1RJ9Roh9NkWHC3afqjL1dcySJnVZUyI4gryXd20MGM8FBOwcZCbxNy9TaRKFWQELF77yKkwqudg2t5aKWe+znqzgHq73Bfne0Hd28j2zCsegQS0HNQaDZpRpRmdyJ+SDqbGxVavtvahph8yzhJtSQLProjT+a5wjJ06kEXDULPVxxggHIhZKWh2+Ti5Cya7oAUqUJnGT5SYFT1UwCPZ1rr7h0FcyICSRM04aYs5uIdxT6WeEA42yaZmE7N5WcpsHeGkC6neVIlCfjcmoKIcmgQC6MaEVOeGKcGHFcUpWM8Wdg1rUfBJHruCTG38OVjuBP3aUvbecMA4iDrL7BSAYhOxSuCB4jL4wRLpaRTvGGhQVDWBQz394UQnn4IFOFBJgXj7vXgb+VTB6e7WSxXjNhkchbls2PrlyXKCpLpDAT975X4+8+D5hbbeeBiomtR0XClr3tJmgq6aEhsTZ/jcEurR0hje3U/2mXHRznb18f5Z97i0hHF2EsCt8jVJc4ceIf7JD7qeZy/k4+vTMiS+f
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: nai-image-pull-secret
      namespace: nai-system
    type: kubernetes.io/dockerconfigjson
