# SealedSecret for NAI image registry credentials
# This sealed secret uses cluster-wide scope so it can be used from any namespace
# NOTE: This requires all target clusters to have the same sealed-secrets controller private key.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: nai-image-pull-secret
  namespace: nai-system
spec:
  encryptedData:
    .dockerconfigjson: AgCFiKjnVhE2dRIHYIjX+V+1cl8VxngDdWzKkskD8EBJo+OscYJ6mBhzz/uDYcrlTN7Y6w2WrwkY6Ibz3yTzGa0dOPAahKuHX29gruVpF1AQsGlfjXZL0bCJ5PqCYSifyqidcZyPuBbRA19348O5VPDU9PdxxJJxlBxjgcxHdhfMzZRZ8Gj+m5VSMVS1jHxLPcZuiau4n+4xaygthF0pS9raso1cVVxcbZCTq72VWRkG/kUFPJnDcpOqf/yzKHL7Wq8r4oQkGyec/RC/xXFofUbYZPYJU85ime/qCZctfH3KfOtEvUoThGM0Xr1Iu67O5SMXkuqbSYRLgjJ+CYgdJaBqM52x+tG+68fi8O2OoR1zo6I6OhhwdK1Ku1WCYdK2hRdnK7i179hL6s//GdkEwYko3PIahzHY4EoT34SzSZjydGkCWbLx4DXqIvWpsdtAzrqHt+oGLLKE/edpdexaW13hBUvhDRQ7sNdPqKI1JJKTWvY80hazO0sUiMo9/fDBS1AR+r6U7mNXWcFp4KdXXjMgRBoWxL+lCl2lBOpsGYwrrcl7hSdqHYN4gJGpEDC4Nq8iG6JUz6ulHwove1CsdaTUG0htktX6O5NwmpL6gfbPxvexpGcPJX4PmmJo1ZZ/5wD4tKLipkjm2Q7k3KDTpnLC6ezrDZ1w0iFKwkRGBhRYJdJJfl8RKHaMCP9/RYwnZiv3+EfRsX9pa4a9cugVN7Npe95cTnmolJEo9qdKHHDXH7UQgh59nbsIEyczV+Fp7eDLW77x+yDZ7lPXvxTVmTGvxjulXcTPqBUkan4uh7kaVij9ogx1mcjz6k84rC9WsJ8wI7h/YG3JG7IJUDF+AxGiqU0lqU+8j52FbBJ1lsHFPES8fKC2l0gBflakXC5ucOw/vahv9EGwXwOQyhg6BTs52+/0v8cG/+/irACOHw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: nai-image-pull-secret
      namespace: nai-system
    type: kubernetes.io/dockerconfigjson
