# SealedSecret for NAI image registry credentials
# This sealed secret uses cluster-wide scope so it can be used from any namespace
# NOTE: This requires all target clusters to have the same sealed-secrets controller private key.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: nai-image-pull-secret
  namespace: nai-system
spec:
  encryptedData:
    .dockerconfigjson: AgCWNeda0nRaIAWzanyH0OZQLpJCaF9HlUdsKCa9dnlBM7CsDRZfK+jbN+ZcZTb+0sXou6A0nuklOjcVQqD3y3wPlLLNlPfNic8R0+QagvVGQ1ZsOEPKKaJHEt8tOo9RaazY3CnQG05oSRb4GBka+IIW2/zRzeq2Ro+u31Vu0f+lXK/7rj973PGFgVG3MkSWIAqV9gYGp9/xZhU6bhVDinjMwZR8AB+CVN1GPgOtK4cNj/WAn0cMWCwXD6SDusOkWkRNuXAtOaW6B3G627XgfU35gPhX9bCFCoW1eSkvYHOLOPU2anw/KN/V3YwyKA2VgkCFaCzHm3o1xeYxYHaDuEW7HHkHVAxd+WVLF4Ed1xQG7yA+rKwJi52nTnDKYQWmbGaDOa8iHTWS2QCu9bBgawL0ifG2qP7d92hRZdHneSj/ZPgo2mxB5dL/Y+08wJ3zRy4cadb2W3yRMrAQl2UprafWQbLb/RL5CdK09iSBytnnCKYO7ES8wkZ6aI1Oc8PqoaY59Gds8Zd8i1kESAFrbzG16uJsmNSPq+7WKZ1FJO7l/2lw2h1dG2ztw1mCQ3c7c12JlXPqTv2v/h8wsHj/MnYcGRFreBQ1cdrVppixpr6HwvbrdqWshS3fN1VmBOMuyZllefnVHc3Gpxo06o44vjt4rA91/2YoIs9qRgAgFKz0kEkfyo8612by5xZcqgH09KQQCLvPgdRpTeIVU0BU9z/Sk9fElViZzoTmAwwmGMudDzmgLA3x/LXFwbAF0YTMeoEfvSp0gOmxQuqZALAMj8Ds+2C3KAN7xLMsW9F8RrmD7eYZQzGbfSWHGCWb2AkM/GOZ/Hp2gVzjFkYNUmoHdXgwsjjA9MxAtfYum+Phl/1Zhlbjj3PD1kppIA44lsFrHonu8/nh7VJQf4HsABUlA5OR8YVohcZRqpyiAFcsqkVQOudlpvxsRzJBHp0efMalPSn6Ect7XDRZ5q2crH/2TUyM6IrYZbYBLsj6Qckjb5P4fFbiap0sWkVxIkPx3fOBY3L414dA0RERzBPRFwo5HteZ7qoejGS7gc8l5BFJ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: nai-image-pull-secret
      namespace: nai-system
    type: kubernetes.io/dockerconfigjson
