apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dm-gitops-dev
  namespace: kommander
spec:
  interval: 5s
  ref:
    branch: main
  timeout: 20s
  url: https://github.com/deepak-muley/dm-gitops-dev.git
