# Add ImagePullSecrets
# Reference: https://kyverno.io/policies/other/add-imagepullsecrets/
# LOW: Automatically adds image pull secrets to pods
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-imagepullsecrets
  annotations:
    policies.kyverno.io/title: Add ImagePullSecrets
    policies.kyverno.io/category: Mutations
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0+
    kyverno.io/kubernetes-version: "1.22-1.30"
    policies.kyverno.io/description: >-
      This mutation policy adds image pull secrets to pods that use images from
      private registries. This simplifies deployment as developers don't need to
      manually specify imagePullSecrets in every pod spec.

      NOTE: Configure the registry patterns and secret names for your environment.
spec:
  rules:
    # Example: Add pull secret for private registry
    - name: add-pull-secret-private-registry
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
      preconditions:
        all:
          # Check if any container uses a private registry
          - key: "{{ request.object.spec.containers[?starts_with(image, 'harbor.') || starts_with(image, 'registry.internal.')] | length(@) }}"
            operator: GreaterThan
            value: 0
      mutate:
        patchStrategicMerge:
          spec:
            # Add the image pull secret if not already present
            +(imagePullSecrets):
              - name: private-registry-credentials
---
# Add pull secret for Nutanix registry
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-nutanix-imagepullsecrets
  annotations:
    policies.kyverno.io/title: Add Nutanix ImagePullSecrets
    policies.kyverno.io/category: Mutations
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Adds image pull secrets for Nutanix container registry images.
spec:
  rules:
    - name: add-nutanix-pull-secret
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{ request.object.spec.containers[?contains(image, 'nutanix.com') || contains(image, 'nutanix/')] | length(@) }}"
            operator: GreaterThan
            value: 0
      mutate:
        patchStrategicMerge:
          spec:
            +(imagePullSecrets):
              - name: nutanix-registry-credentials

