apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    caren.nutanix.com/cluster-uuid: 019afba0-2a28-721d-a629-e2bad7650636
  labels:
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: dm-nkp-workload-2
    konvoy.d2iq.io/provider: nutanix
  name: dm-nkp-workload-2
  namespace: dm-dev-workspace
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneEndpoint:
    host: ""
    port: 0
  topology:
    class: nkp-nutanix-v2.17.0-rc.1
    controlPlane:
      metadata: {}
      replicas: 1
    variables:
      - name: clusterConfig
        value:
          addons:
            ccm:
              credentials:
                secretRef:
                  name: dm-nkp-workload-2-pc-credentials
              strategy: HelmAddon
            clusterAutoscaler:
              strategy: HelmAddon
            cni:
              provider: Cilium
              strategy: HelmAddon
            cosi:
              strategy: HelmAddon
            csi:
              defaultStorage:
                provider: nutanix
                storageClassConfig: volume
              providers:
                nutanix:
                  credentials:
                    secretRef:
                      name: dm-nkp-workload-2-pc-credentials-for-csi
                  storageClassConfigs:
                    volume:
                      allowExpansion: true
                      parameters:
                        csi.storage.k8s.io/fstype: ext4
                        description: CSI StorageClass nutanix-volume for dm-nkp-workload-2
                        flashMode: DISABLED
                        hypervisorAttached: ENABLED
                        storageContainer: default-container-92034737804854
                        storageType: NutanixVolumes
                      reclaimPolicy: Delete
                  strategy: HelmAddon
              snapshotController:
                strategy: HelmAddon
            konnectorAgent:
              credentials:
                secretRef:
                  name: dm-nkp-workload-2-pc-credentials-for-konnector-agent
            nfd:
              strategy: HelmAddon
            serviceLoadBalancer:
              configuration:
                addressRanges:
                  - end: 10.23.130.80
                    start: 10.23.130.76
              provider: MetalLB
          controlPlane:
            autoRenewCertificates:
              daysBeforeExpiry: 180
            nutanix:
              machineDetails:
                bootType: uefi
                cluster:
                  name: ncn-dev-sandbox
                  type: name
                image:
                  name: nkp-rocky-9.6-release-1.34.1-20251126174702
                  type: name
                memorySize: 16Gi
                subnets:
                  - name: vlan173
                    type: name
                systemDiskSize: 80Gi
                vcpuSockets: 4
                vcpusPerSocket: 1
          dns:
            coreDNS: {}
          encryptionAtRest:
            providers:
              - secretbox: {}
          imageRegistries:
            - credentials:
                secretRef:
                  name: dm-nkp-workload-2-image-registry-credentials
              url: https://docker.io
          kubeProxy:
            mode: disabled
          nutanix:
            controlPlaneEndpoint:
              host: 10.23.130.63
              port: 6443
              virtualIP:
                provider: KubeVIP
            prismCentralEndpoint:
              credentials:
                secretRef:
                  name: dm-nkp-workload-2-pc-credentials
              url: https://pc.dev.nkp.sh:9440
          users:
            - name: konvoy
              sshAuthorizedKeys:
                - |
                  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIByxiauNkIB78zerztoOXeNCMxqTLq1kZOI0UGCZvl/V
              sudo: ALL=(ALL) NOPASSWD:ALL
    version: v1.34.1
    workers:
      machineDeployments:
        - class: default-worker
          metadata:
            annotations:
              cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "3"
              cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "3"
          name: md-0
          variables:
            overrides:
              - name: workerConfig
                value:
                  nutanix:
                    machineDetails:
                      bootType: uefi
                      cluster:
                        name: ncn-dev-sandbox
                        type: name
                      image:
                        name: nkp-rocky-9.6-release-1.34.1-20251126174702
                        type: name
                      memorySize: 32Gi
                      subnets:
                        - name: vlan173
                          type: name
                      systemDiskSize: 80Gi
                      vcpuSockets: 8
                      vcpusPerSocket: 1
