---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ndk-image-pull-secret
  namespace: ntnx-system
spec:
  encryptedData:
    .dockerconfigjson: AgCeR5ndXCCilwLpFKI41+xAMV5r+0y7Llm1VOsdFeS19QCdb6Znf6QvF/ot+sUKvvnuKRWDSfqkzJNTtPv8ssgm9kToLwGMpAe6Agr7VxG89X3OoDF5TMLQXqFgu8zN9/3YtBccfVTTJ8IF1zsQB65ma2yBb2vBiNR3jPYYegoQm84/9KWJV3WxvhOGg6FCRBzNBv5Bsx5PgMmDORVWQ9QP9iRIO6rWrZg1N+BmhttU1Ht357HvVL36KzpMydYxbwCvr1vgt5Lz57a4zyg+U1ovDq7cw0quPtCmrJNy/c+vVYGLCTghpu8PrC8RhacRxh6myu/OPFQMBg27jZUvuLaQp1Nfl7FK1uydxyGswDZpEDO10FODE792x2Qsp+DUaP6ajPnt1NjHuzDcjJ4YfXQ3sYJ9N0mbu6VCBCazhV6CLeYmWI/Ra0AlROyIq1DAucIiWWSRk4E//zR97O74WNqoKV79Mlf1suj/wS+gjABFL+Wnv6th76WGrQ2ZzUzzVbuPIpZUevhj5k31Q7KRgrIVtjvTRNLNaTGnOR5Prx7LitLeyltiirPOfUeE1OdUKEKvpVqm9ZI6h9za/l4Ht6LHV4YRduNfRuatg1x6kptmw3TvQdAE8U1rlIeStdTJk72ChsG6SBuiALdzLDLVksB2fzvvhAWg3k64Mbc1qoHz1CIZlpBr9HMnYTkLjkDXMduBhSAwV2BQnd50Ni4fd7mdPffNW4m+yI0WgQURgADmyGz0kNMQh3OQqNMCGsqYUL5CFXu5wpaTnFa2WUROZAIIo+4Xc5FSVIeTN+H/gKfjkS1oA/An2tC/zJjcoV/tD4KpaH9TucnGaeysYt0aAEA7iQsPzYT2Vx5YqCcniBGyT9CpZ3O9esyDqeD1Ee1/xic4ZDLbQDwJODr2TdpY49JC8KI4L/SN9YvpKGDBqw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ndk-image-pull-secret
      namespace: ntnx-system
    type: kubernetes.io/dockerconfigjson
