apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: dm-nkp-workload-2
  namespace: dm-dev-workspace
spec:
  topology:
    class: nkp-nutanix-v2.17.0-rc.1
    version: v1.34.1
    # Uncomment and modify the section below to override base values
    # controlPlane:
    #   replicas: 3
    variables:
      - name: clusterConfig
        value:
          addons:
            serviceLoadBalancer:
              configuration:
                addressRanges:
                  - end: 10.23.130.80
                    start: 10.23.130.76
              provider: MetalLB
          controlPlane:
            nutanix:
              machineDetails:
                image:
                  name: nkp-rocky-9.6-release-1.34.1-20251126174702
                  type: name
          nutanix:
            controlPlaneEndpoint:
              host: 10.23.130.63
              port: 6443
              virtualIP:
                provider: KubeVIP
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          variables:
            overrides:
              - name: workerConfig
                value:
                  nutanix:
                    machineDetails:
                      image:
                        name: nkp-rocky-9.6-release-1.34.1-20251126174702
                        type: name
