# NDK Image Pull Secret for dm-nkp-workload-2
# This sealed secret creates the docker registry credentials for pulling NDK images
#
# NOTE: This sealed secret needs to be re-sealed for the target namespace (ntnx-system)
# The encrypted data below was originally sealed for a different namespace.
# To re-seal, get the public key and use kubeseal with the correct namespace.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ndk-image-registry-credentials
  namespace: ntnx-system
spec:
  encryptedData:
    .dockerconfigjson: AgAFbbMQ3w0rrhC5o9p1XrUqoTaqWknO4MSkRHQE7so+67/+zPIho9oylS2Jp+GEnxfC2bdZ6uSqfLP6wwDNkqi7v+fJjOl4hFMwQRWoTszoEc4wc2kehPc/7Zq10V6Nu95UqRnZBTrpvX4JpRt8x/cMwMKSvQLDveu4JPL4YYpinYbi235nuzWGo7VZMVKzzAeLVnxBsbcjIMPobxIqTwpV+2aVYpKFZERHBps+IH/lkW90AZdtc39lG3mfhkpGVpEpIAU6F2QH2QVGg1uoOjHZLoCP63+5twwCt2SKSlQB9h8lngzvd3Ly3plNOTNK1oEjRZxbfso/M5yBuuRv4M8t6YvBMKs7D2ZbTAHW07LTjEc8Mg69GG6CtcSukEZbpX8RjAx5ISERsUMo1FsYwn/GaBAkUGzDurt/dHIDUZRThkMqE3d7+FCsyWtTBVLANp0E7ERSBKfwWgTxYaVE8cwNvfCHV5Gm8SpgHJfyKITBx5FKytJjYkmBFzLnvelCrLepnG7Y65+NbzvNnNSveiRf6+EMKBR17XLV9wX98iq9knEpmRipyIGd+nTtDc0hvBEhUrvwRGFEkNir4whc+5bFDIlJmnTQtL9fco4nO3KOoRD0I20jZeTmxwxJTeiF/deuRwM+1327dXxRCLeitSr4DOf0KWVLy7Y1mZbZZQhrjX0RLhaM2T+lcCHiauVTAYQseBYfyDCqgdbV5XRr6f9/CLkhjHooBfVb24CDNVdABjrhfjGg2knwE/w8FiMh3uvt5pEFIsUKBLixDeeO4VKAUtvtwSuH5EvSh3dgrOeFq2sX4nkxFxqTaOEUpY2gNVdRBSvs3EDUMx9DFr4LMQbe//4jN0hzt+k6aYIHGOJMDNMBh9aJWKgTxtlpi0guQzQzIkUpL+ekVpGd3we/tmXuRokxzGBdCWwaAl6Uiw==
  template:
    metadata:
      name: ndk-image-registry-credentials
      namespace: ntnx-system
    type: kubernetes.io/dockerconfigjson
---
# Namespace for NDK/Nutanix apps
apiVersion: v1
kind: Namespace
metadata:
  name: ntnx-system
  labels:
    app.kubernetes.io/part-of: nutanix
