# PolicyException to exclude vault namespace from all Kyverno policies
# This is needed because Kyverno webhook is timing out during Vault installation
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: vault-exception
  namespace: vault
spec:
  exceptions:
    - policyName: "*"
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          namespaces:
            - vault

