---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  type: oci
  interval: 1h0m0s
  url: oci://ghcr.io/twuni/helm-charts

