---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  interval: 1h0m0s
  url: https://twuni.github.io/docker-registry.helm
