apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterops-clusters
  namespace: dm-nkp-gitops
spec:
  dependsOn:
    - name: clusterops-workspaces
    # Wait for sealed-secrets to create credential secrets before cluster creation
    - name: clusterops-sealed-secrets
  interval: 5s
  path: ./region-usa/az1/management-cluster/workspaces/dm-dev-workspace/clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-demo
    namespace: kommander
