apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: not-used
  namespace: batcave
spec:
  topology:
    workers:
      machineDeployments:
      - class: default-worker
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "4"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "4"
        name: md-0
        variables:
          overrides:
          - name: workerConfig
            value:
              nutanix:
                machineDetails:
                  bootType: uefi
                  cluster:
                    name: dragon
                    type: name
                  image:
                    name: nkp-ubuntu-22.04-1.29.6-20240905041334
                    type: name
                  memorySize: 32Gi
                  project:
                    name: arvind-lab
                    type: name
                  subnets:
                  - name: ab-overlay
                    type: name
                  systemDiskSize: 80Gi
                  vcpuSockets: 8
                  vcpusPerSocket: 1
      - class: default-worker
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "1"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
        name: pool2
        variables:
          overrides:
          - name: workerConfig
            value:
              nutanix:
                machineDetails:
                  bootType: uefi
                  cluster:
                    name: dragon
                    type: name
                  image:
                    name: nkp-ubuntu-22.04-1.29.6-20240905041334
                    type: name
                  memorySize: 32Gi
                  project:
                    name: arvind-lab
                    type: name
                  subnets:
                  - name: ab-overlay
                    type: name
                  systemDiskSize: 80Gi
                  vcpuSockets: 8
                  vcpusPerSocket: 1                   