apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: nkp-dragon-wld-1
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: nkp-dragon-wld-1
    konvoy.d2iq.io/provider: nutanix
    topology.cluster.x-k8s.io/owned: ""
  name: nkp-dragon-wld-1
  namespace: batcave
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneEndpoint:
    host: "10.124.63.198"
    port: 6443
  topology:
    class: nkp-nutanix
    controlPlane:
      metadata: {}
      replicas: 3
    variables:
    - name: clusterConfig
      value:
        addons:
          ccm:
            credentials:
              secretRef:
                name: pc-credentials
            strategy: HelmAddon
          clusterAutoscaler:
            strategy: HelmAddon
          cni:
            provider: Cilium
            strategy: HelmAddon
          csi:
            defaultStorage:
              provider: nutanix
              storageClassConfig: volume
            providers:
              nutanix:
                credentials:
                  secretRef:
                    name: pc-credentials-for-csi
                storageClassConfigs:
                  volume:
                    allowExpansion: false
                    parameters:
                      csi.storage.k8s.io/fstype: ext4
                      description: CSI StorageClass nutanix-volume for nkp-dragon-wld-1
                      flashMode: DISABLED
                      hypervisorAttached: ENABLED
                      storageContainer: default
                      storageType: NutanixVolumes
                    reclaimPolicy: Delete
                    volumeBindingMode: WaitForFirstConsumer
                strategy: HelmAddon
            snapshotController:
              strategy: HelmAddon
          nfd:
            strategy: HelmAddon
          serviceLoadBalancer:
            configuration:
              addressRanges:
              - start: 172.16.0.17
                end: 172.16.0.19
            provider: MetalLB
        controlPlane:
          nutanix:
            machineDetails:
              bootType: uefi
              cluster:
                name: dragon
                type: name
              image:
                name: nkp-ubuntu-22.04-1.29.6-20240905041334
                type: name
              memorySize: 16Gi
              project:
                name: arvind-lab
                type: name
              subnets:
              - name: ab-overlay
                type: name
              systemDiskSize: 80Gi
              vcpuSockets: 4
              vcpusPerSocket: 1
        encryptionAtRest:
          providers:
          - secretbox: {}
        globalImageRegistryMirror:
          credentials:
            secretRef:
              name: image-registry-mirror-credentials
          url: https://harbor.infrastructure.cloudnative.nvdlab.net/nkp
        nutanix:
          controlPlaneEndpoint:
            host: 172.16.0.15
            port: 6443
            virtualIP:
              provider: KubeVIP
          prismCentralEndpoint:
            credentials:
              secretRef:
                name: pc-credentials
            insecure: false
            url: https://pc.dragon.cloudnative.nvdlab.net:9440
        users:
        - name: konvoy
          sshAuthorizedKeys:
          - |
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8zdJu/B43jajqKe6kGzce7oX4i2iVsom4yKafxziZjKO0LLvYYugv9rwAORCHHwNHbp9ZNdQYe43bRQZj+bxeBqz/yvla6u5oCHHmnS5ZePgyxAjYYfG8GETtY6rl12tgVLQWgaQubCQ2XNlyhkA+z5erSdd+wEStQjKcnzls4o/2v9GTAfjzJT76ZJ17QaghPH2Jh9XuTZQHJfRjT7dzuJA8+oYFbH8BI+y8K84BaO73XTIdPoxYoLKRVhwrAyA8yKenj0sfrRSaOtkwuUFWJdW/ehRboo8PV5R81faTB6R4pwTQcAwnjUbNQD7mjvseLihEJcC7Uz9+od+1I9/zrbmhgHk3ffv9SnhZrVKkQrMxoQIjnfZEmi0U439zeJkyUsXc0Xelr4aYnu46RzeYe2EWshHBN8JS9ug2AfPGeBaiYLqLWcWnJbpixHAF33vYD0Jxxu0vs9W5SNlV9gMq445zk6Mco/utPSMOkZfyXajzBCTKJ+9Zg1I0ZmjFOpM=
          sudo: ALL=(ALL) NOPASSWD:ALL
    version: v1.29.9
