# ServiceAccount for RBAC tests
# This ServiceAccount is used by RBAC policy tests that need a non-default ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
  namespace: policy-tests-violations
  labels:
    test-policy: test-infrastructure
    test-type: infrastructure

