# Network Connectivity Test Job
# Run this periodically to verify firewall rules are correct
#
# PURPOSE: Tests connectivity to required endpoints and reports failures.
#          This complements Gatekeeper policies by actually TESTING if ports are open.
#
# USAGE:
#   kubectl apply -f connectivity-test-job.yaml
#   kubectl logs -n default job/network-connectivity-test
#
# For periodic testing, use a CronJob (see below)
#
apiVersion: batch/v1
kind: Job
metadata:
  name: network-connectivity-test
  namespace: default
  labels:
    app: network-test
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: connectivity-test
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "=== NKP Network Connectivity Test ==="
              echo "Date: $(date)"
              echo ""
              
              FAILED=0
              
              test_port() {
                local host=$1
                local port=$2
                local name=$3
                
                if nc -z -w 5 "$host" "$port" 2>/dev/null; then
                  echo "✅ PASS: $name ($host:$port)"
                else
                  echo "❌ FAIL: $name ($host:$port) - Check firewall rules!"
                  FAILED=$((FAILED + 1))
                fi
              }
              
              echo "=== Internal Cluster Connectivity ==="
              
              # Kubernetes API
              test_port "kubernetes.default.svc" 443 "Kubernetes API"
              
              # CoreDNS
              test_port "kube-dns.kube-system.svc" 53 "CoreDNS"
              
              # Traefik Ingress (internal)
              test_port "kommander-traefik.kommander.svc" 443 "Traefik HTTPS"
              test_port "kommander-traefik.kommander.svc" 80 "Traefik HTTP"
              
              echo ""
              echo "=== External Connectivity (Skip in Airgapped) ==="
              
              # Container Registries (connected environments only)
              # Uncomment these for connected environments
              # test_port "registry.k8s.io" 443 "Kubernetes Registry"
              # test_port "docker.io" 443 "Docker Hub"
              # test_port "ghcr.io" 443 "GitHub Registry"
              # test_port "quay.io" 443 "Quay.io"
              
              echo ""
              echo "=== Summary ==="
              if [ $FAILED -eq 0 ]; then
                echo "All connectivity tests PASSED"
                exit 0
              else
                echo "$FAILED test(s) FAILED - Review firewall rules!"
                exit 1
              fi
---
# CronJob version - runs every hour
apiVersion: batch/v1
kind: CronJob
metadata:
  name: network-connectivity-test-hourly
  namespace: default
  labels:
    app: network-test
spec:
  schedule: "0 * * * *"  # Every hour
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: connectivity-test
              image: busybox:1.36
              command:
                - /bin/sh
                - -c
                - |
                  echo "=== NKP Network Connectivity Test ==="
                  echo "Date: $(date)"
                  
                  FAILED=0
                  
                  test_port() {
                    local host=$1
                    local port=$2
                    local name=$3
                    
                    if nc -z -w 5 "$host" "$port" 2>/dev/null; then
                      echo "✅ $name"
                    else
                      echo "❌ $name ($host:$port)"
                      FAILED=$((FAILED + 1))
                    fi
                  }
                  
                  # Core services
                  test_port "kubernetes.default.svc" 443 "Kubernetes API"
                  test_port "kube-dns.kube-system.svc" 53 "CoreDNS"
                  test_port "kommander-traefik.kommander.svc" 443 "Traefik"
                  
                  if [ $FAILED -gt 0 ]; then
                    echo "WARNING: $FAILED connectivity test(s) failed!"
                    exit 1
                  fi
                  echo "All tests passed"

