# Restrict Secrets Access in Roles
# Reference: https://kyverno.io/policies/other/restrict-secrets-role/
# HIGH: Controls access to secrets in RBAC
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-secrets-role
  annotations:
    policies.kyverno.io/title: Restrict Secrets Access in Roles
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: ClusterRole, Role, RBAC
    kyverno.io/kyverno-version: 1.6.0+
    kyverno.io/kubernetes-version: "1.22-1.30"
    policies.kyverno.io/description: >-
      Secrets contain sensitive data like passwords, tokens, and keys. Access to
      secrets should be carefully controlled. This policy flags Roles and ClusterRoles
      that grant broad access to secrets, especially the 'get' and 'list' verbs
      which can expose all secrets.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: restrict-secrets-clusterrole
      match:
        any:
          - resources:
              kinds:
                - ClusterRole
      exclude:
        any:
          - resources:
              names:
                - cluster-admin
                - admin
                - edit
                - system:*
                # Platform roles that need secrets access
                - kommander*
                - flux*
                - cert-manager*
                - sealed-secrets*
      validate:
        message: >-
          ClusterRoles should not grant broad secrets access. This ClusterRole
          grants {{request.object.rules[?resources[?@ == 'secrets']].verbs[]}} access
          to secrets. Use more specific RBAC rules or document the need.
        foreach:
          - list: "request.object.rules[]"
            deny:
              conditions:
                all:
                  - key: secrets
                    operator: AnyIn
                    value: "{{ element.resources[] || `[]` }}"
                  - key: "{{ element.verbs[] || `[]` }}"
                    operator: AnyIn
                    value:
                      - "*"
                      - list
    - name: restrict-secrets-role
      match:
        any:
          - resources:
              kinds:
                - Role
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kommander
                - cert-manager
      validate:
        message: >-
          Roles granting 'list' or '*' access to secrets require review. Consider
          using more specific access patterns (e.g., get specific secret by name).
        foreach:
          - list: "request.object.rules[]"
            deny:
              conditions:
                all:
                  - key: secrets
                    operator: AnyIn
                    value: "{{ element.resources[] || `[]` }}"
                  - key: "{{ element.verbs[] || `[]` }}"
                    operator: AnyIn
                    value:
                      - "*"
                      - list

