apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: dm-nkp-workload-1
  namespace: dm-dev-workspace
spec:
  topology:
    class: nkp-nutanix-v2.17.0-rc.1
    version: v1.34.1
    controlPlane:
      replicas: 1
    variables:
      - name: clusterConfig
        value:
          addons:
            serviceLoadBalancer:
              configuration:
                addressRanges:
                  - end: 10.23.130.75
                    start: 10.23.130.71
              provider: MetalLB
          controlPlane:
            nutanix:
              machineDetails:
                bootType: uefi
                cluster:
                  name: ncn-dev-sandbox
                  type: name
                image:
                  name: nkp-rocky-9.6-release-1.34.1-20251126174702
                  type: name
                memorySize: 16Gi
                subnets:
                  - name: vlan173
                    type: name
                systemDiskSize: 80Gi
                vcpuSockets: 4
                vcpusPerSocket: 1
          nutanix:
            controlPlaneEndpoint:
              host: 10.23.130.62
              port: 6443
              virtualIP:
                provider: KubeVIP
            prismCentralEndpoint:
              credentials:
                secretRef:
                  name: dm-nkp-workload-1-pc-credentials
              url: https://pc.dev.nkp.sh:9440
    workers:
      machineDeployments:
        - class: default-worker
          metadata:
            annotations:
              cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "3"
              cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "3"
          name: md-0
          # replicas removed - using autoscaler annotations instead
          variables:
            overrides:
              - name: workerConfig
                value:
                  nutanix:
                    machineDetails:
                      bootType: uefi
                      cluster:
                        name: ncn-dev-sandbox
                        type: name
                      image:
                        name: nkp-rocky-9.6-release-1.34.1-20251126174702
                        type: name
                      memorySize: 32Gi
                      subnets:
                        - name: vlan173
                          type: name
                      systemDiskSize: 80Gi
                      vcpuSockets: 8
                      vcpusPerSocket: 1
