apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: Project
metadata:
  annotations:
    kommander.mesosphere.io/description: "Dept 1 Project 1"
    kommander.mesosphere.io/display-name: dept-1-project-1
  name: dept-1-project-1
spec:
  namespaceName: dept-1-project-1
  placement:
    clusterSelector:
      matchLabels:
        env: test
  workspaceRef:
    name: dept-1-workspace
