# Drop All Capabilities
# Reference: https://kyverno.io/policies/pod-security/restricted/require-drop-all-capabilities/
# HIGH: Requires dropping all capabilities (Restricted PSS)
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-drop-all-capabilities
  annotations:
    policies.kyverno.io/title: Require Drop All Capabilities
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0+
    kyverno.io/kubernetes-version: "1.22-1.30"
    policies.kyverno.io/description: >-
      The Restricted Pod Security Standard requires containers to drop all
      capabilities. This follows the principle of least privilege by ensuring
      containers start with no special kernel capabilities and only add back
      what is strictly needed (typically only NET_BIND_SERVICE).
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-drop-all
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-public
                - kube-node-lease
                - capi-system
                - capi-kubeadm-bootstrap-system
                - capi-kubeadm-control-plane-system
                - capa-system
                - capz-system
                - capg-system
                - capv-system
                - caaph-system
                - capk-system
                - capd-system
      validate:
        message: >-
          Containers must drop `ALL` capabilities. Set spec.containers[*].securityContext.capabilities.drop
          to include "ALL".
        foreach:
          - list: request.object.spec.containers
            deny:
              conditions:
                all:
                  - key: ALL
                    operator: AnyNotIn
                    value: "{{ element.securityContext.capabilities.drop[] || `[]` }}"
    - name: require-drop-all-init
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-public
                - kube-node-lease
                - capi-system
                - capi-kubeadm-bootstrap-system
                - capi-kubeadm-control-plane-system
                - capa-system
                - capz-system
                - capg-system
                - capv-system
                - caaph-system
                - capk-system
                - capd-system
      preconditions:
        all:
          - key: "{{ request.object.spec.initContainers[] || `[]` | length(@) }}"
            operator: GreaterThan
            value: 0
      validate:
        message: >-
          Init containers must drop `ALL` capabilities.
        foreach:
          - list: request.object.spec.initContainers
            deny:
              conditions:
                all:
                  - key: ALL
                    operator: AnyNotIn
                    value: "{{ element.securityContext.capabilities.drop[] || `[]` }}"

