# Restrict Volume Types
# Reference: https://kyverno.io/policies/pod-security/restricted/restrict-volume-types/
# MEDIUM: Limits allowed volume types
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-volume-types
  annotations:
    policies.kyverno.io/title: Restrict Volume Types
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod, Volume
    kyverno.io/kyverno-version: 1.6.0+
    kyverno.io/kubernetes-version: "1.22-1.30"
    policies.kyverno.io/description: >-
      In addition to blocking hostPath volumes, the restricted profile limits
      volumes to certain safe types. This policy restricts volume types to the
      following safe list: configMap, csi, downwardAPI, emptyDir, ephemeral,
      persistentVolumeClaim, projected, secret.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: restricted-volumes
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-public
                - kube-node-lease
                - capi-system
                - capi-kubeadm-bootstrap-system
                - capi-kubeadm-control-plane-system
      preconditions:
        all:
          - key: "{{ request.object.spec.volumes[] || `[]` | length(@) }}"
            operator: GreaterThan
            value: 0
      validate:
        message: >-
          Only the following volume types are allowed: configMap, csi, downwardAPI,
          emptyDir, ephemeral, persistentVolumeClaim, projected, secret.
          Found disallowed volume type in spec.volumes[].
        foreach:
          - list: "request.object.spec.volumes[]"
            deny:
              conditions:
                all:
                  - key: "{{ element.keys(@)[?!contains(['name', 'configMap', 'csi', 'downwardAPI', 'emptyDir', 'ephemeral', 'persistentVolumeClaim', 'projected', 'secret'], @)] | length(@) }}"
                    operator: GreaterThan
                    value: 0

