---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: ">=1.15.0-0"
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: sealed-secrets-controller
  storageNamespace: sealed-secrets-system
  targetNamespace: sealed-secrets-system
  upgrade:
    crds: CreateReplace

