---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dm-nkp-workload-1-pc-credentials
  namespace: dm-dev-workspace
spec:
  encryptedData:
    credentials: AgCiF0bcHF7NRuUAIbNcCUEi0WBlzI6NgsTWPl0CdjhVRGJDTlmdY1vhbu43bGczCvgXZDQIDui/wb3poupSYf++uN0qb94K7f5pUq8BCzK7iqlfJ3RMNZK717Gw8EsorZ1M5t62mys0c7KJ0vJAG1Pz3oLQ1y2Do9/NSoUfihpCdJtx4sHhBthbfi3nt+1b9zDoT287lKLbAEol9kC7r9APxj9HqFJQ7NonZniiLBVzGzGIREkzUwiwxddGj+iBJoynpxjK722aSIk476O3YWD0otNaXilzL2LRoAgNCNai0Rzx52svqG/uLb8EXRC1NMmge7DwOYBItTXTdIZGhbwYQVtUycsepJkY8UKtk6oe2vW4TruNQHVzmKSibyMcJbV5bHzhXpjDkHhHQHeR9b4awNRktG7Ca5RExLQY5nd/GaHmaKBoq4L2Np0N0Thb5a1shUbiu/aNQTe37OLCFJ7e6ftqIbcAKUXGSUaLuhqsq/R6ximuxpMn9sUjpsXbZrBKNRid6lpFsm9b5clpym2HUanTrg/nlJ1KX0xjfyAPPRFun7sGiXZ2FtBOEH+94Tk70kNh1A9BCIgIvY0zornwBqENKHFYQbl/JT+4NwPobEP2OAqE5Ob0RXzqQN8rF2pDonMmIMbxUEec80Vvc6BgQmo72CpbuC7DcsFv8RKIyss1LMgvxYUcY5Etl77fCJlceTR1+pPRrwxZZDekBIqrBzaPZf66JCnf/ZsuzkSMRPGS4dPNHuZdxU70O1rzNkxnP9aRyoGHG2rMtz/4N+DYHBKk3TcKNyM8IxvXNuTF0BPEh2lN5QvpzN9Eh70j20UxgzQKd3ZmUsFxljqVAD4VUmLhcxwCgjq7
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: nutanix
        konvoy.d2iq.io/cluster-name: dm-nkp-workload-1
        konvoy.d2iq.io/provider: nutanix
      name: dm-nkp-workload-1-pc-credentials
      namespace: dm-dev-workspace
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dm-nkp-workload-1-pc-credentials-for-csi
  namespace: dm-dev-workspace
spec:
  encryptedData:
    key: AgBNfXAFm0TnTp80M1bELm7aO/nu4oQlNnlSqz9WTIdYzpuDWWReOSIUGJQhRTvXXhswnAPe1/S0V2aa2+j+BDSih9tSGeDuHv5j53IXnWxQLTrFk0jJtb8z8yhEDpNX9RiBCJk/sb95raGRpoPtbS9PsQKFJg3smi407M9OaNhXHMG1ZU9Tr0CsSEAOLGX1VP4tQH7/dd+VT05IhRkMQeGp6ClSkqDg3FkdpL9177Z762yM73SkMQnxg+NCzl2aE0jYNQ9rclinWA80Cgi4/XaiD+jNRb1RZQ/FaBbo2mw3pSLxDlc37wS9FY2psE/7wQvwszwGoAsmB3DTYNajeAXVn72gl/9O9fgGLpxFvDm3cpzOtK34CIYNAfuXemAv27RfwCXTFM3cGzl0lIk6ZpEMQqE0y9CNRGse6X7lpHt/H/Xmz4X8R5t3vZIlLsLwqLgDQlmk3UC3CjOsuXsC8X4d7mWpGKyuplHqWxPY9UggWf7yBDSLM9VbRck5OzFykWhFbFO/u1fv2b+gmCh4F/wA2OWbtWWM+P7q8xydCvwSnamooPKOOnEtaziWY7OYmjY1sk6AadObVgj6SpPKoNWKIL4pZce83uyF0Y+3jpJzCT7fB1KotHQVzPtM35vjktZgI7HMJxBODO9lSg+C+14mIUfUGiDW8dL/Y9WYZlCPc4ApM6rnffeNgt3zSahna0K9TFO9/O4HprcX5XfZhMBxW5LNiuOnsqx5s4UmAZXNTZsh31/IbFNyNvzY0fjqWr91KTBwzPBrIKYyV9AMmlDu
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: nutanix
        konvoy.d2iq.io/cluster-name: dm-nkp-workload-1
        konvoy.d2iq.io/provider: nutanix
      name: dm-nkp-workload-1-pc-credentials-for-csi
      namespace: dm-dev-workspace
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dm-nkp-workload-1-pc-credentials-for-konnector-agent
  namespace: dm-dev-workspace
spec:
  encryptedData:
    password: AgCcmE7GEN337Zp9b3erJXBipOBZjkFTa/eov80VhEiQ+3+YmKEK7ry4zOs4ckFGCEvDzUFUUhSk5jbeZ9gdVDlVVt0m1i8GNgR0ggCSunB8+NQcFLwkpJS3BwNzei8nmgfBSzIalJZjmpEIJXjILWGVxu1tzHeNdew3erz6gzy3Dsb7vvOmV8SE7SnT0R4O7KVGB9vcmf1XAGQNt2y+TrQrIc+AjrCjihCUZq9eLf1SAdCgnl3N+WUeoHjipyw5dXwurVwJnC3mQEnAitVZPkLqoug6OapZ5ZjGf162DPG/BpBASaG2rS26a7EANGL8goGn6Y2PnIVj10d0glSDgcUwDmXsVZO229WlBikpi/Dcao2iPgOF1pzivmk8X/fV18j/PegNqIyOcOrUlH4v2iLezzFwRzQG7xacOQqM4VoE3kX5H/X79wqh6EKkYq+eDuK+gbFyVWj/1TLSFIS9WpDdQGrzYfaH9xTnpDQGgM+vh8pluBfdIyujinVK9HyhofKT7sJcY4RmJN+mJoayCQMiWhXxyVCKY9tS7WY1yGXC1BsCzQNM0zID4qMewHQZQdtWR6Cc+5WrKpHHKTqDPN3VaHvU9s/4VH4M98xepYBajF6uGf7K56y0NxWusOP3HCmW5cSCQ2lXV3f7ZaTYaQSw/J2d6V9OhVdq3j0TbYr65G4PaP5ZuZCZn9f8BiMQ/ZALMBaxPHkPRQ6PKxv+EedCP9PyOI1R04skqHfCExjSEQ==
    username: AgAbiSHGj4Sbmp4zaWpaR/PpLaaH5tE/1UM5ruRPA7vKcNUhCE++f4bZhGB6MjPD8h4cvOkdKOx97HtdDbVlrMgNO31SJG8bHgTElvFBh/0T+G7IWFlpivblCXW8PVGlyQGq+1VBgpC0GjzP3cvMTxV7EMmG6kQxNG83Wi/xblpOUCZgCUuK9LR37wpGeqMYwsYtPeCScTVn+U+m1ELKioMifrGXFUAtZ34qBNXR2H2d5bnkSJfRdCFW5tOy9Xdf8+jnzgspucj8Pih5y+C+v9AsBCJEVXupZaJcE+sIvkSzDTA9MC/8q3O2ucEYppkZuGwsNAF/FK2kWFrRIvZJbUWu9yEdcIy+VMqcKrPJWur6oJJkzTYbKCRuon0CSSUJXro1tHqk7GTvmluZaQ62qK29jGQjyy9z9BqqZeCo8SIW4E6s7Irq71ncmilXixGxbJn/zob314RU6FRqFzQ4gI8cshgW0/8ie3Pnu8Yd8Kqk4kei8U8JFCP2ICsfkrSwfqWkzGL5DVkh2JGLtbnO4Z62dhRZyzLhk0sRXdMPXf7F9tsPaaSdL0T1eBkek7w7855AAPb1uY4LKnpGFeZ2ivQe6l+ZwDlDMergkY6CvKLfMn7K9+cyZht1NQGlmO2P9wesC4qIpACgMKkmuUO8aIFD3rMtFrbAA+4MwNr08avCCjOs46AB9o6ZcncduTHjFmAOru8fFDgEsXq8+Jo=
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: nutanix
        konvoy.d2iq.io/cluster-name: dm-nkp-workload-1
        konvoy.d2iq.io/provider: nutanix
      name: dm-nkp-workload-1-pc-credentials-for-konnector-agent
      namespace: dm-dev-workspace
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dm-nkp-workload-1-image-registry-credentials
  namespace: dm-dev-workspace
spec:
  encryptedData:
    password: AgCYk2GsWUaTQJDUhn+jhAupfuUsoDRv3fknfN+6BwyuNKJLxXlnODfeeBvimK92d1aoamjgxzUtNAbB2qI9OfK1xYgr98xlNSeIEidWfZpGM10ooMz7ccJWICfyWT7yHEynL6wYBKXtIWcnc0ewWqE4Fr3cGBMhRoCIHoW67tTP5hHZIyw2E/8/iw318h2WvXn8lQguteHiL1JoagHuUJeRnif77WjX5fYeyWaSmGD4Kx/fEIjVjPAbWSe50pVuut3xAUwAO+mruJiZxlrkhxLnWuYtKAXsjPbBooXyeT6Yr/efLRzom7iunl69FfGSq7cxY6LhemIPLzLxuHwmdMizRwSRmjP+KZEgW/6YmiB6DsIuH7mJxTMPxxDW0HsV1ZEH4rLmOkAi/zV3JD5Zntvte4booOW1qbb/arOej+zXKsiCuvG39sb5zM0pCiE0ugSZ03U6GsJLCBatbyrZmD5wCdxXMH+cb2D9/ju4900oxUzOGZuY3WEJOAYyvoKnTKos9w5aS8r/OruNhYUTLbvAW/ce8hmrPzKmmX9kvr+rqHbmVHMDOH8XlvS8cjJJ/2REbvR/eBHhRKu0hmJhHC2FHiQxaIJ5nNBteL3W8cRlFP+ZL20Xi+bvtb3uPYGSqFbyHfpOFhSC2Mrza8T205TdmWtp4UDnMHbUEEZpDMH84Y30lc6SATcxITXFuF9er0x0pLTidvrimfunyA==
    username: AgA6WzWvUWPPQeKP3gijroADENn69YukhMgN/Z3TW7JJo47oE1WG1NSJNrr0RrcVg3tQueKB6E7bWd6Vsc9iGHiMuUyxVGbZbQvVr5Q6WbIUNbjnIzBeiOqWqcjE8BUQZIT4HE56QT2W7KiC3RQdxmiKMrtGYVyvib6kMijSY43hW/lao3qJyNxPUxU+1/HExY4rsB0QSWtr4fk9y5M7EBZetPOsPVbu5A8b51eHVkLMImsy3fwZG1eyqWo4j1044u8Vbvtv2PuRKSuKkIZBhlJV4ODRrv8o4Kx8gmrCe6VJCsImhLm4xqJ6knBnM7pBB6pzltuafkwnkOiltLeWjkO0egWECGoyldaBBpeZVuW76UDae3x0ggniHyGLM8dKEjYw7JeD4I1y0BFYAiBajlkyNPb1GjYuhze27+N/m0bubWqOjy/RxZG/t3xUj0VLjlsalxAYsCcNLWXLa+shuV93F9DzGsai1IbC6hDToqLm/CQDTutXT1Qi90JnIMe45TCDOEt5emWiYBg5g0ZiIABaTVjzT4v6GqnDvvoL9Q83VC/7l6XL6ZbXqzILh+xJlsQnLnxPUPoZnuk2NRLaQvoajncVDjMdmD6+y6FtXVCXEMHxHwclF7cHPCJfF37EH7fDGqWxcwNtJiBSFNDOY8s7xaRrN1cCFGiEbdofHDCj1y+KER6/fUPb0IhuCRewCNL9w2CPEBhgJsvkMQ==
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: dm-nkp-workload-1
        clusterctl.cluster.x-k8s.io/move: ""
      name: dm-nkp-workload-1-image-registry-credentials
      namespace: dm-dev-workspace
    type: Opaque
