---
# Kubemark Hollow Nodes for Scale Testing
#
# IMPORTANT: Kubemark does NOT create standalone clusters!
# It adds "hollow" worker nodes to an EXISTING cluster for scale testing.
#
# Usage: Update CLUSTER_NAME to match an existing cluster in your workspace
# (e.g., dm-nkp-workload-2 or dm-nkp-workload-2)
#
# These hollow nodes simulate real worker nodes but run as pods in the
# management cluster, consuming minimal resources (~50Mi each).

# Configuration - Update these values
# CLUSTER_NAME: The existing cluster to add hollow nodes to
# Set this to one of your existing clusters (dm-nkp-workload-2 or dm-nkp-workload-2)

---
# MachineDeployment for Kubemark hollow nodes
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: dm-nkp-workload-2-kubemark-md-0
  namespace: dm-dev-workspace
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "5"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "100"
spec:
  clusterName: dm-nkp-workload-2
  replicas: 10
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: dm-nkp-workload-2
      cluster.x-k8s.io/deployment-name: dm-nkp-workload-2-kubemark-md-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: dm-nkp-workload-2
        cluster.x-k8s.io/deployment-name: dm-nkp-workload-2-kubemark-md-0
        node-type: kubemark-hollow
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: dm-nkp-workload-2-kubemark-md-0
      clusterName: dm-nkp-workload-2
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: KubemarkMachineTemplate
        name: dm-nkp-workload-2-kubemark-md-0
      # Note: Using v1.30.0 because Kubemark image v1.34.1 doesn't exist in quay.io registry
      version: v1.30.0
---
# KubemarkMachineTemplate - defines the hollow node configuration
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: KubemarkMachineTemplate
metadata:
  name: dm-nkp-workload-2-kubemark-md-0
  namespace: dm-dev-workspace
  labels:
    cluster.x-k8s.io/cluster-name: dm-nkp-workload-2
spec:
  template:
    spec:
      extraMounts:
        # Mount containerd socket for pod scheduling
        # See: https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/issues/22
        - name: containerd-sock
          containerPath: /run/containerd/containerd.sock
          hostPath: /run/containerd/containerd.sock
          type: Socket
---
# Bootstrap configuration for hollow nodes
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: dm-nkp-workload-2-kubemark-md-0
  namespace: dm-dev-workspace
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: "{{ ds.meta_data.local_hostname }}"
