# SealedSecret for NDK image registry credentials
# This sealed secret uses cluster-wide scope so it can be used from any namespace
# NOTE: This requires all target clusters to have the same sealed-secrets controller private key.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ndk-image-pull-secret
  namespace: ntnx-system
spec:
  encryptedData:
    .dockerconfigjson: AgCnWPWCLTqGOVkGjKu+4YLy7IaP0nbmDuxpTuJhZCjLX67kay0dj6cXRAh1bYZKmWFkWhazBWNQjO8Bw1yaYA4/SPnLsVCKdvhj7/73wdhaaknSy2yUxVNUjEjWboxQOHC5YKOcV9aQ8f044CPeNGDXRcqEnAO+jmg3wW10LCBVEZXlFKNZt8RSgu9dA0tq4OuIxLWNLPR4z6MCSu819nZJRa/6ZSJP+J4oJiMgOT0GM1cFJQy+U1o/lpBstJS3tx/0l4F1nMr2TMKLsdTa3sdwYMvJ4VyJNSXXElRFNk5OmsURd7MsQtent1Oq/w0AIwIDqVjI2AVafbyzsX1hzpWUFTvPoKVCny/vBKKX3OG848tnXT17/nxGelbQmaMThnvTN21vd7PPM2mgb2u+yfTrllwJnStDknTYr4AS2YPreuO5gPx8lo9eNZPuInjKQ9g/cxVxxObZeU5Gp/O9AqBUjxr+t7WVF5EqQiuCJoXujoipEBzFq6N4YqYpjmwYssZC4bajrdusbc9rp/IKqrHRGBI90FDR1KYJ4S+yM/LpKFdQuU7CcyZNpvA5zIGaIhbLb3BbKhbzsHUH0u8Y/w3FvzP950+MO+KKVspiDrRnpJvAWofJKk/DUNGXoSKRuoyMr2lOJFCae08sHy24DZo45TerQUGzYc+5UmUvow0nQoAUGMTVMLerFSCuqzCNqbjALp9XYdQLWpvyt+ZFW2/JJvvxZ9YYZlHr3G/0dVUFpct+y7ng8P5nSjPtiHIbmgtpNPbrKoqMElXq5YcMsFEpkqGGxmGYaGqhYFO1wfvcXHleN5A87pUFJlxPmM87K0h3MaS3YjUwkyuDF8blbcHIxLNvNWZkGcYrmFnVdWuhfzo6Hpz+s95y3a53W4sdhU8wjRsGww3+RPJdN3qDlWKvP41otvJTGsZRvQBKvlsZ4gEdApgg6eg+JcOxnkR6Bg1pXMcVBanK
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ndk-image-pull-secret
      namespace: ntnx-system
    type: kubernetes.io/dockerconfigjson
