# SealedSecret for NDK image registry credentials
# This sealed secret uses cluster-wide scope so it can be used from any namespace
# NOTE: This requires all target clusters to have the same sealed-secrets controller private key.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ndk-image-pull-secret
  namespace: ntnx-system
spec:
  encryptedData:
    .dockerconfigjson: AgAVYMuM6KU7TnfjbZWcZW47NLOnFvxMeYWGeaLF3nkQ4vJNVdO+ZWkIwN7r/zmQ+uRhm1VAcXSUVKF+VI1dxycUTfH8pCKGn8+W3FeFFadKlNV8ZamGHp3xgqhHpg8GUI9fqHfoQNGWilPqUNUqyfq4hc8R5DneDO6g76IJVQXrj5YCE/cfIkrJb9rgkuC1S8D1H+bqutqGdBqwEzxRVnS2nZ8HuG+GaEF5YyigisUuiwErKcL66wZz6GZZgAIh4idcH93QSlgcvrx5Kf7ymeYaw0eoc+ubrTH8QvthEFOud5P+FN8ynDjOtlRwQyYXYhQLsyofSXvqq0WIQHYEHfBWxLBXixFuqCWeBU6lB4RbA/28iPb7ILl9XppFYcngSHDMMtktNT52ghFRZXCK9xJ+ag/HcyLt3nONhEPFQ9mWequfQMoPUFr1mvbS3Yys/AixQRSLjS2tYXOZvp+mNcnsuciOIZ5kfKzw61DC/axj7ViB5wWb2QLNTZ9WnUQTe/JkGYZvZsvNMRDdyr4RS9LbgqcnsaboE0zwTt5PfTeLiOFKTJ5NCN4JWxIiVD84RWSoveHR6wB2+zkCE3wfNxCCdqqnb0qChfqg+LQeo8K2IV/pboSgQEdvtaIzYnvoZ0uYjautRAunvp9o2RBNyAXb+fWHmZw2veS+nvb1LMRfMn3hEcY7Ls7fXweQCJVugEOU2eRzqvMH7tfu8Zren8AO20p3YXAzSGRYB8QA1uyc7+Nmb9owV5spvfQafKL+xIam9lWoMhQAXlGmPq/z4KJT0xJP2evEJ7eHqpxNdsyUehFziZInT4v93MuTZJgdYDAGt7EjHF/4E6MQe68pwh6FCkq9rutJwkgHabyhhNZ8gwCWhAkFr7aFWhAv7zvv8SANTYV0ofeaKOuoMTLWDc+0i7kunS6spLT9NQ33gw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ndk-image-pull-secret
      namespace: ntnx-system
    type: kubernetes.io/dockerconfigjson
