# SealedSecret for NDK image registry credentials
# This sealed secret uses cluster-wide scope so it can be used from any namespace
# NOTE: This requires all target clusters to have the same sealed-secrets controller private key.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ndk-image-pull-secret
  namespace: ntnx-system
spec:
  encryptedData:
    .dockerconfigjson: AgB26+KvlzYiWLiX5pzjjSmu+yLzgI4E9hPTEorA64kj9iWTkwR9HYxesGQiLaW0HKL48gxqAvu8dvS3GnW+wnoW4hbQHLfV3+uNeZ8EAggEP+LNiB0hhdV+4Rz/8R82pD+lljLVSz7MrCndYdBsUFG5CI/Kga6YjAGSueB60loO3TvhMN+xA7o4DEQw0QbV9NncSOj3bOVb8I21xBmi6jweG4Rvon/dLhU17+WDEeJB/XE92ZukLxjmM4y6gD90QviwZnyIWcKaBymFuMkuHrrWm3VNa8N7j/Ml8EUTsN5cOAeo9cjdsbPhysVh5MExzhPo0gZ/wRPOnO7JaCH6SGMXUQ0pVTSHWO5717N7J2+6aONoETQ5Lgub4CahaLk85iS3trSIx+Cnr9OZkuQfmZuHIiO4FIZafTofLGPkLQEm/CSzqlzA4/RSzkSN721OBVsXdcGdQ1860F34UB4prpxN35M5MDIlVG8Aev3OgZ8rH32ujdw+8dHhYNtROem4yaUT/xXrvvYe1qHW6imPEVCFXL9n9txHtQqUa2zcf+KPBYiL/rpasdFp3iRu341Z6YkYVyDDulbfAXoTQsrRGCrvkVzK+8+niTWj9ebe6L2Fq+v0hpzhdqiM7+TofglZf/nWfjhsgkuHGrxgiswugzQR9ngeMyXrD/XllQlXD7wJyGkws2MEQ84wiB4z6J9+PLfgyVaZq8kL0yYZ9HR9fs00TVyrW3hooiQx3yjFdRnwMwhTTxo8f4/EYnXlG8KNw9Ml4wGY9RBOMRy8DsiZfFHENvy4SAHNKHEbKodUYerNoG5i38ig334u1e8eJkEcDKvw1YqbyepTG39kGtCsvm1TehaDu7qdf7GubPYB6dL9huQ98DYv4VoFmu/AVV3tmjiMwGEWk7cRVpsRbYqIY8iozHZVKHjnd4K23okkJQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ndk-image-pull-secret
      namespace: ntnx-system
    type: kubernetes.io/dockerconfigjson
