# SealedSecret for NDK image registry credentials
# This sealed secret uses cluster-wide scope so it can be used from any namespace
# NOTE: This requires all target clusters to have the same sealed-secrets controller private key.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ndk-image-pull-secret
  namespace: ntnx-system
spec:
  encryptedData:
    .dockerconfigjson: AgAFkMNtFc9fTqIScMU/Ki9UDj9lrrtz5C6F8kY8wEoLP8OvnM5i3jttcfVI+99f+hBVpBOMFixKv8bWtQDqwyE4qfVovNl/Yr1UmsjXYe0jX60fkt+TxGVptdbLWD1UQfT2uAtI80QewWNIuq2b0IXk5I+OZvyUw6i/IImY8eok0X0QgdsaMBT3u0Nc5+IGwRoPvW7tU/neNIiXdiN1G78YvSXblVCKOSrU9p6hH+JInuD1u1qDb5glbgMlPMb5bcHPpb4nE7YNaUTX3f4oQ+MC/WXlGZByGQA4wvn8afr88006es8EjbTm9mdNsab/3DZx7BN/q/onVGVZsMscIMiv9wREGvOVNwH6TPWeZzBuAZX72IuwC0oOF6/JX016z3q36TNDC/Y727W2BKmEPfx773yPPea9ODAGCAorMHD9k4LnoMYodBOK8iEOyDn5rzRlL1W5mzKCcbs41g+gJnPrOwJhGKrqAA6wOv/tfHgVZJL2uFFI9eAdAkLDmjbD4f/J9wkOGRJ6CS5xRKVjj4TSp6m306bUuhxCcYheIl9aXPUjrfYzHNTOjJB4Bl3BgzSzWElSizOetYYO1xUgEJqEZQl8uGRCe7jjAK9nKRuwi+zUMPnKdq2R4qO36dD5FBoqzwfAeYGC71EYg3vSQ1pXynRf8MpTX+Nx5pzWjpmtl9/Ae0VXtksKsZYmbC+W1P2qG7JBahW3RxGAXw/K28x+GeWQoBsshiCLFE7eU+/L7KNeZ0nj0kUDrDEzRvRV2OiJQK9gtUsx4DOvSO74F9kX7UdmDgy4YQBwoQCq+WD2ZiJ1+fkShUc1L3okU1FCtayVOGau1CZmBwfocIaYjIYMeuUvjomc6LVcPU7Moco56F7zG6FnXVpYw+tYv5rGumOaGAhRwJS+VSmyWcBxw+MBNYvHKW5ORNFtJuFXzvs0XsT9c0Wvf+WocslBGEFZ9/6L0UuV3FQvuFMy/RS6R8oE7Jn0EkVEWUcXvlkRoMpsYH3iwiSBKEFB5aU96yFNTM34pYjRPFx7jgseAd6JW5S8Wb+BxDNb55EKaBZ5
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ndk-image-pull-secret
      namespace: ntnx-system
    type: kubernetes.io/dockerconfigjson
