# SealedSecret for NDK image registry credentials
# This sealed secret uses cluster-wide scope so it can be used from any namespace
# NOTE: This requires all target clusters to have the same sealed-secrets controller private key.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ndk-image-pull-secret
  namespace: ntnx-system
spec:
  encryptedData:
    .dockerconfigjson: AgBSo9OnS6nMJK4ucRdrUWjduy1W+Tv1J8Slc6k1neVyTb2hpuvKF3IRPizjRHikd9o3COiukOtIx0cTkgh0ut7pIkb4WHK9jW3c4+W+OeHG1fpx2xP0ss526MhCPdBXTpONlg4T+VFBgxFMWcg5xmjyqmU7tuvT0jre08zkSQLR8s1wPTxRbL4Hm26Fll624Qnf5hTdrOMNbkFXy2DuPLHA2WXUpiOTQ8pSdhDTK9/JNFVIZjN/v6GYiInBujh38Jqy0G6TmnrLV04s1WUVl35YcKJNvnfflnPtySitLicL+vnDIMnQoy4+q5LTnL699mn/WM/cCvsS8e5hJVQJP0CWabdp8xc3x0/J82Neg4Y65Uis/e5s3nOwqRCqQ9x/Sphp28npvl7AP5Rk42wS77Cc7SNIyKmxQB689YhuYE1oa/gnDY83vhCDDlfJLyjwlQAgK1mOsDxQaCbuhTu/SDNME99Mab6OJ72lUJnue/DacWH6VBEbbQemrKWKmbwPHZF2vH2vUqqsDK0S+kDIX96/C4IRlJSVnQySqOzc7xRAe2hfJT75tUJCrWApxRZCD9yYqa3iT2tMmlHZ/Ud5TYq1crkGqSOuGTIjNK2hi96N6oNRCPHw1tNBGGGTH47lqzVEqHDI+rB0zrnuhloCarcOTJRT5H0PlzWMyM5Wm1t76dpDZUUKJHFv+vyJ6ntlilpuI9JM0L8vL92AwaaFkqTZ02lCupIH2VfMSL0A+sYwouol3cFP2lcKVOU44mjvPiJFy+PHQIZkYCfb/yzM0Su26Ba6x/prWmYIrSP8GLRfqcLC1ptw47ueayaj72nx7vRvEYptE6VdKslo2v+7UNxfmbEDK9BK3Lg/4CG7qnC86QIelHPGdNBtmOyUFAzPDuMi2nVB1TH9w09rkwyziarC8t0rcTlBLTTyzbPW5qapTFAM4eTiOYKSS3Rkear3eTkdOfGdfS+v
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ndk-image-pull-secret
      namespace: ntnx-system
    type: kubernetes.io/dockerconfigjson
