# SealedSecret for NDK image registry credentials
# This sealed secret uses cluster-wide scope so it can be used from any namespace
# NOTE: This requires all target clusters to have the same sealed-secrets controller private key.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ndk-image-pull-secret
  namespace: ntnx-system
spec:
  encryptedData:
    .dockerconfigjson: AgCb9Y7j0+4b/6gLh9nMs7C9cWmxfzujzrAVjAyv9yKQHKkx1mVj58gcOxzrF+wGKlEZRiNJ9NOZpNbTlMi+Z0ZqwhhsIYtLnWcgzS1CQ1msZRVffRSzc0ek/Kyq0tS4zRTe70zHQ3Ww7sPL/rOzeIl0MUf82cN9hTQgv0Eo56u57MqjbatLBq2pjgT2b5ZVJrugyOA4kvkacK5vc/WwrO0GB/N52i68CYaV+35dgVf6uU4Rtwj4ea8nrfWEckWappCuaarwrWlIdiTehLK6X0dIVU9UK0/5c+/KFvCXjm+SwQL9f+Yqy1/LWBw03PPkTHSzJyxbpLydXB6D7NxLa6GmMyz97Vv1U08EYRVMj+NRcrVbDj2/nGIvVcm8oO6eloOc4jYpIk9lqffea3I1cJhHam8uofckuN/pwc7lALd1Gd6ix+lgjy3wEWUrm0E/vNRAlDoWnMcRGyJgfzKAxK2LeSLGf/HvBGG3+ACzo+GOVV3gLKDMwgRDJUyGIPgHdWDpxVCL+bQYHoG1N19Cvyr6Rz/SvOTcrcuk7axUYkv2/HV0KtbMMLI8OFYBXRtMpvXYolDB66oUjHjdMq/58699A8tmlyOmUvZ6pqKENrA1WCfJZOUQYhCOmPszBAs43BAOpmJT32cd8WkpHj1Fgy5rE15y403V5jkvWbPf+9G2S+obNhGx1hkbyybdT2SbXFy+lTcy4Gmp22cqd/OZpQ5cXrMCWkjtZ/5MGBOg9HVBkjAMAx2Jo1O1H1bvryeufUZNM2l28ihfc6GhYs5BSEha9BsAv4QquxqLQHG9CnIfwBoN1WSMhib/Z2D5580NED4imFNPDduu/PJb+ex/FYMH3CmGrBI7q5ZPLZtljeN/JVKFwSHFmn3B8zOvtQ9Em8yil4CEkPxd1/HK1Os+F+uJ5vKuK/7Amp5EHiY/0A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ndk-image-pull-secret
      namespace: ntnx-system
    type: kubernetes.io/dockerconfigjson
