# SealedSecret for NDK image registry credentials
# This sealed secret uses cluster-wide scope so it can be used from any namespace
# NOTE: This requires all target clusters to have the same sealed-secrets controller private key.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ndk-image-pull-secret
  namespace: ntnx-system
spec:
  encryptedData:
    .dockerconfigjson: AgC0jVFr7O3aXkITuVjsK3ezg16jh4sepCQ+KOOKMXwjLPpIcGO44ziHDlKNA4EWKuEKKRMwXtFsTm+TbG+pu4u/Ebj6iaaB0Jdad/qp2GJHjcNMfjtq1oDAOkW3oVxIwL7re7mvBOwFtcsWi7+STwFBVKUMIBu/ZZwUultwvQbbiSAqh5QbS9aR0hzUfsRZYZiXpfpkItXKavfdfQy8tgu4ZTPqAnY1yE4BMPAoABCcySZphTv63Mv37+JqXdqEyR/f8cQwSEmY+AnyO01Sydmv7MSzpeERGyC/fikOL/gomHhzJ5CyskPguWU9cwzYUCfKtyv9uGYh1uA/HGWWPDnetE9+aLLq//zSXzrRNrmLpl6G4o8KzIPc0SyCpuqCuL5/aK02QK8EUwA6I9bGOYw359zisGAthA/+ULVHoiDtEDU99zAryjF51tj0oJimoRPubXoFvC7UylxfxGTsT07OXxkC6EAdtJtlMXyh112FNZfe3YOZsI/7H6dH2OhdmUcclOwei/574Ad1LSAmWyNT6Rh39p44fuJGormQDCMYwzVmH1N2RtYVoviZXPpc6yvhZBcY7kIIN7uIZOpDF8stUq4g2IvLGouHkEbS5nBSiyA6sxJOXaMqbjGaUrhapZLxJOwCmwgfLxXHcy6J+DDvx6YbJBDTD21rrwTBYvaO/Ea99/BbxMiasvMp7g2NslxUeCgDk8SV2xhwYMxtPOuaTHAyLf51wht56yN+q91JB7jUXT7/CmmXhZumomLo/zI0bc+TBCZT3pv81ulcg4vQQJPOMMZOLk9h6tTDqVuPf1PTKPU5lpTPitZnuhEKB0z8j+NF/K+t2wOlagoYGqh9ri/vydtYHFxW+t1A8PF4wfMN9Mv2cC+4z7GFUY2FzyI0uPb0OkeV4oeacNo6M00Kgm2sPXWUoilJPaTTKw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ndk-image-pull-secret
      namespace: ntnx-system
    type: kubernetes.io/dockerconfigjson
