# SealedSecret for NDK image registry credentials
# This sealed secret uses cluster-wide scope so it can be used from any namespace
# NOTE: This requires all target clusters to have the same sealed-secrets controller private key.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ndk-image-pull-secret
  namespace: ntnx-system
spec:
  encryptedData:
    .dockerconfigjson: AgDCP5b70OQe9gJK3owpqNBQ9LJZXQSHV/XnmFz1uFSg1sFvzOhSwxTK8EbT6hb3+kIPpf1Te8H1XqmsWWUnZONvkcANO6vLHpMoYjtW+x5/KaVjbnqq0ALHuOZB4oSqrqxCEHv03WHwNTzWOlbmmWG7LeOlurCq7sE/+ZAWVxqckyEb4JxV7M5pK4armyZXnGw48AxfEZsRstTOyab5yejivl2ccX1etiZc2mRVzqITSsoVFUvsViyCC7n0izRVAw/GaW/ww89BjGv7XWVp5GWhF2Tic4qTXgNO9b9RgsuIzzDfg7Plqpppk1b+vJfrSUz4zF+csTUtkA4afGqSZCM+V2dxJorRC3nyhczE+5D4FOtn7fY4Rq9u9CDagkB/8lu7HlM61Bk76uqhpmGVWbf8onUOtMqY3OiVMje/YQlGNPXEOkpRJ89GolVybVNqfAGipOb6HUGFfFhzioBbmjl/6oW+cR9f1ZDuU6n/kY8rjCqNd0zRn2sT2AJu6sgnImYwpymGdwqbONJpUVLSFz1OVfr5rztOSKuJlGRyOJ9nhB9WQ54+Q+GMHXFB299njVjetA/JhuNmJvLNLTJBe1Ynk9EQ1kETBOGXtBDYVpvtK2UB7TviJoyoQN9THcm0ZobIcO/fT9ORDe/aTYdntqLdm7OrCwa0NeAu/HObsrGxsTTGZC/zd9hmOYjtxphcjVjeBwEi6J9FVRYgO7Ka6EYlUUQ4pI6LMWbJ+yIG405/kp+Mnn5OPv31CUrsv3Ct8HnNrUVXB7pdDIzgjHYIoUygtOokiElRdWsX7NZI9msG7YnV+nwhi0jexDvRr/ifPTk8Lh7XU9nNNEeHGxzIOqKfvmdeL0u0JJZvnlD6/3clpY4eYGG6Qf9AYIscd8ddQ0YWeSIkzt9UAkNWt3k8JT7DRQg/qw2GpA7OoLR6lg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ndk-image-pull-secret
      namespace: ntnx-system
    type: kubernetes.io/dockerconfigjson
