# SealedSecret for NDK image registry credentials
# This sealed secret uses cluster-wide scope so it can be used from any namespace
# NOTE: This requires all target clusters to have the same sealed-secrets controller private key.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ndk-image-pull-secret
  namespace: ntnx-system
spec:
  encryptedData:
    .dockerconfigjson: AgBSf7rtBSlJcEU1zch8ntcGHjjunMCYCeRXg2goCY3ia0WtB6pncLAIiEZWQ3riuJENOlrfe1y0cXSjZuy02zoA6cB/h5y4D8sRv4+ppWPXU4mNrG7q6VZc0kOySvNNLe7zYmUDk721qYD4f+iTlKb9bsxupOobB9xER8pMhzusDIuOl1aASYw3L5cR98a96570CUfWNd8l46MFDLFHhKzZEJHClxVNi6DQ0p5J1nqjMa5YLH6zOr9xc2jlfcoXSO60L7lPjptN7yS1in7rhu1Zdrk+MMQynAndvcwCw/ngncfUgve+3asKHIWoMRWs5gMYP5ZqzFplKpyb0DcN7hP4nUUDCb6mXYg6qgwJxmGldRK8cljrHU0M7hgUTTjjY6AN/rtsjG2uuIanBA8W0tvH/PgScU/bpkMhg1SkWdgq/hGUSM1DSBS+pqFkFT545Uz2PhIh7h7Ez/O5d/8/MWM6llrU+3YKMSBcxUamiSe6DUigfhdorK+0mW8tM91uZUtduvZBB8Grd4PN1gixwZeIsvRbwH5PRXQRytwlMhCc5xkjNeC6lxX36pD1gHJ4fX1XQkTUI4ykKoz/ZdQ5Aw089p+WMEnESOdtU3fJ9IKvr878R078X9BynHBR+/ycCrrFxTIXkzzvG4QpdHPKG/v1t0ob0T7TUOc3ah1q8aNurTPLm4Z5sqgnOYzoLuzkT50YJROhvn8VvfdjwMLPX01U5YfHB1V7Ut6UDnikQrEBV1a0uWo6HkJFEh/xmZ8CqkWXklu9TEuvnt21jvLCib68ty7ofwyiD6hzQXakThuHa1Bq1sNiu3spgaJypkteKgP1PyQ7sIILLXHUwE2peYoRyN3aFc9y4bawHgqhJ9x6ieXHfwTQsgAgnaLlpz8vle7sRooSvm2CJHEQcm/UyTtnZ+oNs0beCvoyZVgWKw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ndk-image-pull-secret
      namespace: ntnx-system
    type: kubernetes.io/dockerconfigjson
